### ISSUE TITLE
Q: should ipython configurations from within emacs be encouraged?

### ISSUE THREAD

**Issue by pank** [astoff/comint-mime#24]
If `comint-mime-prefer-svg` is non-nil, the ipython config might be overwritten (e.g. `~/.ipython/profile_default/ipython_config.py`).  Is it desirable for emacs to configure ipython? I guess it maybe is, since most other ipython consoles are "smarter" than emacs these days (e.g. the qtconsole) so maybe you want to reserve `ipython_config.py` for those? On the other hand, I would find it confusing if my ipython settings are "overwritten" via comint-mime.

Maybe it's fine to just have such config nil by default?  
Or maybe it's better to point out how to configure ipython in reasonable ways in docstrings and the README?

**Comment by astoff** [comment]
That's a tricky question. In principle I'd say the config file should be respected. That said, this file probably includes some "console-dependent" (such as supported image formats) and some "console-independent" settings (such as preferred color schemes), and it's also probably hard to tell the two classes of settings apart from each other.

I don't use an ipython config file, if you could give me some insight on what kind of settings people typically do there it might help with those design questions.

**Comment by pank** [comment]
I mostly use it to improve the output of `matplotlib_inline` tbh. I am not sure what they are generally used for but [there's an introduction](https://ipython.readthedocs.io/en/stable/config/intro.html).

```python 
c = get_config()

c.TerminalInteractiveShell.confirm_exit = False
c.InteractiveShellApp.extensions = ["autoreload"]
c.InteractiveShellApp.exec_lines = ["%autoreload 2"]

c.InlineBackend.figure_formats = {"svg"}
c.InlineBackend.print_figure_kwargs = {'bbox_inches': None}
c.InteractiveShellApp.exec_lines = ["%matplotlib inline"]
```

**Comment by jabirali** [comment]
> Maybe it's fine to just have such config nil by default?
Or maybe it's better to point out how to configure ipython in reasonable ways in docstrings and the README?

I personally don't think it's a good idea to ask the user to reconfigure IPython to make this work:

- I regularly use IPython inside Emacs, iTerm2 (via [itermplot](https://github.com/daleroberts/itermplot)), and VSCode (via "Jupyter: Create interactive window"). Currently, all of these solutions inject the settings they need, so that I only have to put console-independent things in my IPython config. If this feature is removed from `comint-mime`, I'd have to make a  complex config that detects whether IPython is running in Emacs and adapts...
- Currently, `comint-mime` + `tramp` works excellent together – even to servers where I haven't pulled down my dotfiles (I regularly work on some HPC clusters where I don't bother syncing all my dotfiles). If this setting injection is removed from `comint-mime`, I'll have to start syncing my dotfiles to all those servers to retain the SVG plot feature. Part of the reason I like `tramp` is that it works fine on remotes that I haven't configured, and this would break that workflow.

My opinion would therefore be that it's better to keep the current default, where the setting is `nil` by default but injects some IPython config if the user turns it on.

> I don't use an ipython config file, if you could give me some insight on what kind of settings people typically do there it might help with those design questions.

I might also chime in here, since I do use an IPython config (albeit quite simple). I have two IPython dotfiles:

```python
# ~/.config/ipython/profile_default/ipython_config.py

import IPython

c = get_config()
c.TerminalInteractiveShell.prompts_class=IPython.terminal.prompts.ClassicPrompts
c.TerminalIPythonApp.display_banner = False
```

```python
# ~/.config/ipython/profile_default/startup/start.py

import os
import sys

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

mpl.style.use("bmh")

def revtex():
    plt.style.use("~/.config/ipython/profile_default/startup/revtex.mplstyle")

os.system("clear")
```

The first one is the actual IPython config file, where I set IPython settings. Currently, that just makes things look minimal.

The second one is the "start-up routine". I use it to prevent having to type `import numpy` every time I restart IPython, as well as to set a decent default theme + a bunch of shortcut commands to change between custom Matplotlib themes that I use when trying to fit various journal styles (I included one such example here, but have more functions locally).

**Comment by astoff** [comment]
Okay, I agree with your rationale, @jabirali. In fact, in [dREPL](https://github.com/astoff/drepl/) I've taken the "settings injection" approach you described to set the shell prompt, and now I'm planning to expand this approach to allow submitting arbitrary configuration options.  Of course if a configuration file exists, it will be presumably be read as well, and since the Emacs-injected configuration happens later, it will take precedence.

Since from my perspective everything is clear now (although not necessarily implemented), I will close the issue.

(By the way, if you guys like comint-mime you might like that other package as well ;-)).
